enabled_plugins:
  backends:
    - personal
  services:
    - personal
    - favorites
    - lookup
    - reverse
  views:
    - default_json
    - headers_view
    - personal_view

views:
  displays:
    default_display:
      -
        title: Firstname
        field: firstname
      -
        title: Lastname
        field: lastname
      -
        title: Number
        field: number
      -
        title: Favorite
        type: favorite
  profile_to_display:
    default: default_display

services:
  favorites:
    default:
      sources:
        - personal
  lookup:
    default:
      sources:
        - personal
  reverse:
    default:
      sources:
        - personal

rest_api:
  https:
    listen: 0.0.0.0
    port: 9489
    certificate: /usr/local/share/ssl/dird/server.crt
    private_key: /usr/local/share/ssl/dird/server.key

auth:
  host: auth
  port: 9497

consul:
  scheme: http
  host: consul
  port: 8500
