sync:
  image: n3llyb0y/wait
  links:
    - dird
    - confd
  environment:
    PORTS: "9489 8000"
dird:
  image: dird-test
  ports:
    - "9489:9489"
  volumes:
    - "./etc/xivo-dird:/etc/xivo-dird"
  links:
    - "confd"
confd:
  image: python:2.7
  volumes:
    - "./confd_data:/tmp"
  command: /tmp/run_confd
