version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - dird
    environment:
      TARGETS: ""
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
  dird:
    image: xivo-dird-test
    ports:
      - "9489"
    volumes:
      - "./etc/xivo-dird/config.yml:/etc/xivo-dird/config.yml"
      - "./etc/xivo-dird/sources.d:/etc/xivo-dird/sources.d"
      - "../../..:/usr/src/xivo-dird"
      - "./ssl:/usr/local/share/ssl/dird"
