version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - auth
      - confd
      - consul
      - dird
    environment:
      TARGETS: "auth:9497 confd:8000 consul:8500 dird:9489"
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
  confd:
    image: python:2.7.13-stretch
    volumes:
      - "./confd_data:/tmp"
    expose:
      - "8000"
    command: /tmp/run_confd
  consul:
    image: python:2.7.13-stretch
    volumes:
      - "./consul_data:/tmp"
    expose:
      - "8000"
    command: "/tmp/run_consul"
  dird:
    image: xivo-dird-test
    environment:
      XIVO_UUID: "1a2cd704-ed32-4fa3-918a-d32b0609de81"
    ports:
      - "9489"
    volumes:
      - "./etc/xivo-dird/config.yml:/etc/xivo-dird/config.yml"
      - "./etc/xivo-dird/templates.d:/etc/xivo-dird/templates.d"
      - "../../..:/usr/src/xivo-dird"
      - "./ssl:/usr/local/share/ssl"
  auth:
    image: p0bailey/docker-flask
    expose:
      - "9497"
    volumes:
      - "./auth_data:/tmp"
      - "./ssl:/usr/local/share/ssl"
    command: "python /tmp/mock-xivo-auth.py 9497"
