enabled_plugins:
    backends:
        - privates
    services:
        - privates
    views:
        - default_json
        - headers_view
        - privates_view

views:
    displays:
        default_display:
            -
                title: Firstname
                field: firstname
            -
                title: Lastname
                field: lastname
            -
                title: Number
                field: number
    profile_to_display:
        default: default_display

rest_api:
       listen: 0.0.0.0
       port: 9489
       certificate: /etc/ssl/server.crt
       private_key: /etc/ssl/server.key

auth:
    host: auth
    port: 9497

consul:
    host: consul
    port: 8500
