sync:
  image: n3llyb0y/wait
  links:
    - auth
    - dird
    - db
  environment:
    PORTS: "9489 9497 5432"
dird:
  image: xivo-dird-test
  links:
    - auth
    - db
  ports:
    - "9489:9489"
  volumes:
    - "./etc/xivo-dird/config.yml:/etc/xivo-dird/config.yml"
    - "./etc/xivo-dird/sources.d:/etc/xivo-dird/sources.d"
    - "../../..:/usr/src/xivo-dird"
    - "./ssl:/usr/local/share/ssl"
auth:
  image: p0bailey/docker-flask
  ports:
    - "9497:9497"
  volumes:
    - "./auth_data:/tmp"
    - "./ssl:/usr/local/share/ssl"
  command: "python /tmp/mock-xivo-auth.py 9497"
db:
  image: xivo/xivo-dird-db
  ports:
    - "5432"
