enabled_plugins:
    backends:
        - xivo
    services:
        - lookup
        - favorites
    views:
        - default_json
        - favorites_view

views:
    displays:
        default_display:
            -
                title: Firstname
                field: firstname
            -
                title: Lastname
                field: lastname
            -
                title: Number
                default:
                field: exten
            -
                title: Mobile
                default:
                mobile_phone_number:
    profile_to_display:
        default: default_display

services:
    lookup:
        default:
            sources:
                - xivo_america
                - xivo_asia
                - xivo_europe
    favorites:
        default:
            sources:
                - xivo_america
                - xivo_asia
                - xivo_europe

rest_api:
       listen: 0.0.0.0
       port: 9489
