enabled_plugins:
  backends:
    csv: true
  services:
    lookup: true
    service_discovery: true
  views:
    default_json: true

views:
  profile_to_display:
    default: default_display

services:
  lookup:
    default:
      sources: {}
  service_discovery:
    template_path: /etc/wazo-dird/templates.d/
    services:
      xivo-confd:
        template: confd_disco.yml
        lookup:
          default: true
    hosts:
      1a2cd704-ed32-4fa3-918a-d32b0609de81:
        uuid: uuid
        service_id: id
        service_key: key
        tenant_uuid: 9b9c2b06-d2be-413f-8113-36239f4b866d

rest_api:
  https:
    listen: 0.0.0.0
    port: 9489
    certificate: /usr/local/share/ssl/dird/server.crt
    private_key: /usr/local/share/ssl/dird/server.key

bus:
  enabled: false

service_discovery:
  enabled: false

consul:
  scheme: http
  host: consul
  port: 8000
  token: the-master-token
