enabled_plugins:
  backends:
    sample: true
  services:
    lookup: true
    favorites: true
  views:
    default_json: true
    headers_view: true

views:
  profile_to_display:
    default: default_display

services:
  lookup:
    default:
      sources:
        sample_plugin: true
      timeout: 0.5

rest_api:
  https:
    listen: 0.0.0.0
    port: 9489
    certificate: /tmp/ssl/dird/server.crt
    private_key: /tmp/ssl/dird/server.key

bus:
  enabled: false

service_discovery:
  enabled: false
