enabled_plugins:
  backends:
    csv: true
  services:
    lookup: true
  views:
    cisco_view: true
    csv_backend: true

views:
  profile_to_display_phone:
    test_fallback: test_fallback
    test_sorted: default

services:
  lookup:
    test_fallback:
      sources:
        test_fallback: true
    test_sorted:
      sources:
        test_sorted: true

rest_api:
  https:
    listen: 0.0.0.0
    port: 9489
    certificate: /usr/local/share/ssl/dird/server.crt
    private_key: /usr/local/share/ssl/dird/server.key

bus:
  enabled: false

service_discovery:
  enabled: false
