enabled_plugins:
  backends:
    personal: true
  services:
    personal: true
    favorites: true
    lookup: true
    reverse: true
    cleanup: true
  views:
    default_json: true
    headers_view: true
    personal_view: true
    personal_backend: true

views:
  displays:
    default_display:
      -
        title: Firstname
        field: firstname
      -
        title: Lastname
        field: lastname
      -
        title: Number
        field: number
      -
        title: Favorite
        type: favorite
  profile_to_display:
    default: default_display

services:
  favorites:
    default:
      sources:
        personal: true
  lookup:
    default:
      sources:
        personal: true
  reverse:
    default:
      sources:
        personal: true

rest_api:
  https:
    listen: 0.0.0.0
    port: 9489
    certificate: /usr/local/share/ssl/dird/server.crt
    private_key: /usr/local/share/ssl/dird/server.key

bus:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest
  enabled: true

service_discovery:
  enabled: false
