enabled_plugins:
  backends:
    sample: false
    ldap: true
    wazo: true
    csv: true
    csv_ws: true
    personal: true
    dird_phonebook: true
    unknown: true
  services:
    lookup: true
    favorites: true
    personal: true
    reverse: true
    source: true
  views:
    backends_view: true
    default_json: true
    headers_view: true
    personal_view: true
    cisco_view: true
    wazo_backend: true

views:
  displays:
    default_display:
      -
        title: Firstname
        default: Unknown
        field: firstname
      -
        title: Lastname
        default: Unknown
        field: lastname
      -
        title: Number
        default:
        field: number
      -
        field: favorite
        type: favorite
  displays_phone:
    default:
      name:
        - display_name
      number:
        -
          field:
            - phone

  profile_to_display:
    default: default_display
  profile_to_display_phone:
    default_phone: default

services:
  lookup:
    default:
      sources:
        sample: true
      timeout: 0.5
  favorites:
    default:
      sources:
        sample: true
      timeout: 0.5

rest_api:
  https:
    listen: 0.0.0.0
    port: 9489
    certificate: /usr/local/share/ssl/dird/server.crt
    private_key: /usr/local/share/ssl/dird/server.key

bus:
  enabled: false

service_discovery:
  enabled: false
