enabled_plugins:
  backends:
    csv: true
  services:
    lookup: true
    favorites: true
  views:
    default_json: true
    csv_backend: true

views:
  profile_to_display:
    default: default_display

services:
  lookup:
    default:
      sources:
        csv: true
        csv_2: true
  favorites:
    default:
      sources:
        csv: true
        csv_2: true

rest_api:
  https:
    listen: 0.0.0.0
    port: 9489
    certificate: /usr/local/share/ssl/dird/server.crt
    private_key: /usr/local/share/ssl/dird/server.key

bus:
  enabled: false

service_discovery:
  enabled: false
