enabled_plugins:
  backends:
    wazo: true
  services:
    lookup: true
  views:
    default_json: true
    wazo_backend: true

views:
  displays:
    default_display:
      -
        title: Firstname
        field: firstname
      -
        title: Lastname
        field: lastname
      -
        title: Number
        default:
        field: exten
      -
        title: Mobile
        default:
        mobile_phone_number:
  profile_to_display:
    default: default_display

services:
  lookup:
    default:
      sources:
        wazo_america: true
        wazo_asia: true
        wazo_europe: true
      timeout: 1

rest_api:
  https:
    listen: 0.0.0.0
    port: 9489
    certificate: /usr/local/share/ssl/dird/server.crt
    private_key: /usr/local/share/ssl/dird/server.key

bus:
  enabled: false

service_discovery:
  enabled: false
