sync:
  image: n3llyb0y/wait
  links:
    - dird
    - america
    - europe
    - asia
  environment:
    PORTS: "9489 8000 8000 8000"
dird:
  image: dird-test
  ports:
    - "9489:9489"
  volumes:
    - "./etc/xivo-dird:/etc/xivo-dird"
  links:
    - "america"
    - "asia"
    - "europe"
america:
  image: python:2.7
  volumes:
    - "./confd_data:/tmp"
  command: "/tmp/run_confd america"
europe:
  image: python:2.7
  volumes:
    - "./confd_data:/tmp"
  command: "/tmp/run_confd europe"
asia:
  image: python:2.7
  volumes:
    - "./confd_data:/tmp"
  command: "/tmp/run_confd asia"
