version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - auth
      - dird
      - slapd
      - db
    environment:
      TARGETS: "slapd:389 db:5432 dird:9489 auth:9497"
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
  dird:
    image: xivo-dird-test
    ports:
      - "9489"
    volumes:
      - "./etc/xivo-dird/config.yml:/etc/xivo-dird/config.yml"
      - "./etc/xivo-dird/sources.d:/etc/xivo-dird/sources.d"
      - "../../..:/usr/src/xivo-dird"
      - "./ssl:/usr/local/share/ssl"
  slapd:
    image: nickstenning/slapd
    environment:
      LDAP_DOMAIN: xivo-dird.wazo.community
      LDAP_ORGANISATION: acme
      LDAP_ROOTPASS: xivopassword
    ports:
      - "389"
  auth:
    image: p0bailey/docker-flask
    expose:
      - "9497"
    volumes:
      - "./auth_data:/tmp"
      - "./ssl:/usr/local/share/ssl"
    command: "python /tmp/mock-xivo-auth.py 9497"
  db:
    image: wazopbx/xivo-dird-db
    ports:
      - "5432"
