sync:
  image: n3llyb0y/wait
  links:
    - auth
    - dird
    - slapd
  environment:
    PORTS: "389 8500 9489 9497"
    TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
dird:
  image: xivo-dird-test
  ports:
    - "9489"
  volumes:
    - "./etc/xivo-dird/config.yml:/etc/xivo-dird/config.yml"
    - "./etc/xivo-dird/sources.d:/etc/xivo-dird/sources.d"
    - "../../..:/usr/src/xivo-dird"
    - "./ssl:/usr/local/share/ssl"
  links:
    - auth
    - db
    - slapd
slapd:
  image: nickstenning/slapd
  environment:
    LDAP_DOMAIN: xivo-dird.wazo.community
    LDAP_ORGANISATION: acme
    LDAP_ROOTPASS: xivopassword
  ports:
    - "3899:389"
auth:
  image: p0bailey/docker-flask
  ports:
    - "9497:9497"
  volumes:
    - "./auth_data:/tmp"
    - "./ssl:/usr/local/share/ssl"
  command: "python /tmp/mock-xivo-auth.py 9497"
db:
  image: wazopbx/xivo-dird-db
  ports:
    - "5432"
