# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/xivo-dird/conf.d/

source_config_dir: /etc/xivo-dird/sources.d

# Database use for the storage of personal contacts and favorites
db_uri: postgresql://asterisk:proformatique@localhost/asterisk

# REST API server
rest_api:

  # HTTPS Configuration
  https:

    # Listening address
    listen: 0.0.0.0

    # Listening port
    port: 9489

    # SSL files
    certificate: /usr/share/xivo-certs/server.crt
    private_key: /usr/share/xivo-certs/server.key

    # SSL ciphers
    ciphers: "ALL:!aNULL:!eNULL:!LOW:!EXP:!RC4:!3DES:!SEED:+HIGH:+MEDIUM"

  #CORS configuration. See Flask-CORS documentation for other values.
  cors:

    #Enabled by default
    enabled: True

    #Allow JSON preflight requests
    allow_headers: Content-Type, X-Auth-Token

# Connection info to the authentication server
auth:
  host: localhost
  port: 9497
  verify_certificate: /usr/share/xivo-certs/server.crt

# Event bus (AMQP) connection information
bus:
  username: guest
  password: guest
  host: localhost
  port: 5672
  exchange_name: xivo
  exchange_type: topic
  exchange_durable: True

# Connection info to the contact storage server (Consul)
consul:
  scheme: https
  host: localhost
  port: 8500
  verify: /usr/share/xivo-certs/server.crt

enabled_plugins:
  backends:
    - personal
    - xivo
    - csv
    - csv_ws
    - ldap
    - dird_phonebook
  services:
    - config
    - favorites
    - lookup
    - personal
    - reverse
    - phonebook
    - cleanup
  views:
    - api_view
    - config_view
    - default_json
    - headers_view
    - personal_view
    - phonebook_view
    - aastra_view
    - cisco_view
    - polycom_view
    - snom_view
    - thomson_view
    - yealink_view

views:
  displays:
    default_display:
      -
        title: Name
        field: name
        type: name
      -
        title: Number
        field: phone
        type: number
      -
        title: Mobile
        field: phone_mobile
        type: callable
      -
        title: Favorite
        field: favorite
        type: favorite
      -
        title: Personal
        field: personal
        type: personal
  displays_phone:
    default:
      name:
        - display_name
        - display_name1
        - display_name2
      number:
        -
          field:
            - phone
            - phone1
            - phone2
        -
          field:
            - phone_office
            - phone_office1
            - phone_office2
          name_format: "{name} (Office)"
        -
          field:
            - phone_mobile
            - phone_mobile1
            - phone_mobile2
          name_format: "{name} (Mobile)"
        -
          field:
            - phone_home
            - phone_home1
            - phone_home2
          name_format: "{name} (Home)"
        -
          field:
            - phone_other
            - phone_other1
            - phone_other2
          name_format: "{name} (Other)"
  profile_to_display:
    default: default_display
  profile_to_display_phone:
    default_phone: default

services:
  lookup:
    default_phone:
      sources:
        - internal
      timeout: 0.5
  favorites:
    default:
      sources:
        - personal
  service_discovery:
    template_path: /etc/xivo-dird/templates.d
    services: {}

# Service discovery configuration. all time intervals are in seconds
service_discovery:
  # the address that will be received by other services using service discovery.
  # use "advertise_address: auto" to enable ip address detection based on
  # advertise_address_interface
  advertise_address: auto
  # if advertise_address is "auto" this interface will be used to find the ip
  # address to advertise. ignored otherwise
  advertise_address_interface: eth0
  advertise_port: 9489
  # the number of seconds that consul will wait between 2 ttl messages to mark
  # this service as up
  ttl_interval: 30
  # the time interval before the service sends a new ttl message to consul
  refresh_interval: 27
  # the time interval to detect that the service is running when starting
  retry_interval: 2
  extra_tags: []
