enabled_plugins:
  backends:
    - phonebook
  services:
    - lookup
  views:
    - default_json

views:
  displays:
    default_display:
      -
        title: Firstname
        field: firstname
      -
        title: Lastname
        field: lastname
      -
        title: Number
        field: number
  profile_to_display:
    default: default_display

services:
  lookup:
    default:
      sources:
        - test_pbook

rest_api:
  https:
    listen: 0.0.0.0
    port: 9489
    certificate: /usr/local/share/ssl/dird/server.crt
    private_key: /usr/local/share/ssl/dird/server.key
