version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - auth
      - dird
      # - confd  # not confd, we WANT it to take time to start
    environment:
      PORTS: "dird:9489 auth:9497"
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
  dird:
    image: xivo-dird-test
    ports:
      - "9489"
    volumes:
      - "./etc/xivo-dird/config.yml:/etc/xivo-dird/config.yml"
      - "./etc/xivo-dird/sources.d:/etc/xivo-dird/sources.d"
      - "../../..:/usr/src/xivo-dird"
      - "./ssl:/usr/local/share/ssl"
    depends_on:
      - confd
  confd:
    image: python:2.7.13-stretch
    volumes:
      - "./confd_data:/tmp"
    command: /tmp/run_confd
  auth:
    image: p0bailey/docker-flask
    expose:
      - "9497"
    volumes:
      - "./auth_data:/tmp"
      - "./ssl:/usr/local/share/ssl"
    command: "python /tmp/mock-xivo-auth.py 9497"
