enabled_plugins:
  backends:
    - csv
  services:
    - lookup
  views:
    - default_json
    - headers_view

views:
  displays:
    default_display:
      -
        title: Firstname
        default: Unknown
        field: firstname
      -
        title: Lastname
        default: Unknown
        field: lastname
      -
        title: Number
        default:
        field: number
  profile_to_display:
    default: default_display
    new_profile: unknown_display  # broken

services:
  lookup:
    default:
      sources:
        - my_csv

rest_api:
  https:
    certificate: /usr/local/share/ssl/dird/server.crt
    private_key: /usr/local/share/ssl/dird/server.key

auth:
  host: auth
  port: 9497
