services:
  favorites:
    wazo-internal:
      sources: {wazo-internal: true, personal: true}
      timeout: 2.9
  lookup:
    wazo-internal:
      sources: {wazo-internal: true, personal: true}
      timeout: 2.9
  reverse:
    wazo-internal:
      sources: {personal: true}
      timeout: 1
views:
  profile_to_display:
    wazo-internal: Display
sources:
  wazo-internal:
    unique_column: id
    name: wazo-internal
    first_matched_columns: []
    extra_search_params: {'context': 'wazo-internal'}
    type: xivo
    searched_columns: [
      firstname,
      lastname
    ]
    format_columns:
      phone: "{exten}"
      display_name: "{firstname} {lastname}"
      name: "{firstname} {lastname}"
    auth:
      host: localhost
      password: XXXXXXXXXXXXXXXXXX
      port: 9497
      username: wazo-dird-xivo-backend
      verify_certificate: False
    confd:
      host: localhost
      https: true
      port: 9486
      timeout: 4
      verify_certificate: False
      version: '1.1'
