dird:
  image: dird-test
  ports:
    - "9489:9489"
  volumes:
    - "./etc/xivo-dird:/etc/xivo-dird"
  links:
    - "phonebook"
phonebook:
  image: python:2.7
  volumes:
    - "./data:/tmp"
  command: python /tmp/httpd.py
