version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
    environment:
      TARGETS: "dird:9489 auth:9497"
  dird:
    volumes:
      - "./etc/wazo-dird/conf.d/asset.csv_with_pipes.yml:/etc/wazo-dird/config.yml"
      - "./etc/wazo-dird/sources.d/asset.csv_with_pipes.my_test_csv.yml:/etc/wazo-dird/sources.d/my_test_csv.yml"
      - "./tmp/data/asset.csv_with_pipes.test.csv:/tmp/data/test.csv"
