version: '3'
services:
  sync:
    depends_on:
      - dird
    environment:
      PORTS: "dird:9489"
  dird:
    volumes:
      - "./etc/xivo-dird/conf.d/asset.no_auth_server.yml:/etc/xivo-dird/config.yml"
      - "./etc/xivo-dird/conf.d/asset.no_auth_server.no_auth.yml:/etc/xivo-dird/conf.d/no_auth.yml"
      - "./etc/xivo-dird/sources.d/asset.no_auth_server.sample.yml:/etc/xivo-dird/sources.d/sample.yml"
