version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
    environment:
      TARGETS: "dird:9489 auth:9497"
  dird:
    volumes:
      - "./etc/wazo-dird/conf.d/asset.in_plugins_d.yml:/etc/wazo-dird/config.yml"
      - "./etc/wazo-dird/plugins_d/asset.in_plugins_d.my_test_csv.yml:/etc/wazo-dird/plugins_d/my_test_csv.yml"
      - "./tmp/data/asset.in_plugins_d.test.csv:/tmp/data/test.csv"
