version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
    environment:
      TARGETS: "dird:9489 auth:9497"
  dird:
    image: wazo-dird-test
    ports:
      - "9489"
    volumes:
      - "./etc/wazo-dird/conf.d/asset.ldap_service_down.yml:/etc/wazo-dird/config.yml"
      - "./etc/wazo-dird/sources.d/asset.ldap_service_down.test_ldap.yml:/etc/wazo-dird/sources.d/test_ldap.yml"
