version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - slapd
      - db
    environment:
      TARGETS: "slapd:389 db:5432 dird:9489 auth:9497"
  dird:
    volumes:
      - "./etc/wazo-dird/conf.d/asset.ldap_city.yml:/etc/wazo-dird/config.yml"
      - "./etc/wazo-dird/sources.d/asset.ldap_city.test_ldap.yml:/etc/wazo-dird/sources.d/test_ldap.yml"
  slapd:
    image: nickstenning/slapd
    environment:
      LDAP_DOMAIN: wazo-dird.wazo.community
      LDAP_ORGANISATION: acme
      LDAP_ROOTPASS: wazopassword
    ports:
      - "389"
