version: '3'
services:
  sync:
    depends_on:
      - dird
      - swagger-validator
    environment:
      TARGETS: "dird:9489 swagger-validator:8080"

  swagger-validator:
    image: swaggerapi/swagger-validator
    ports:
      - "8080"
