version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - db
    environment:
      TARGETS: "dird:9489 auth:9497 db:5432"
  dird:
    volumes:
      - "./etc/wazo-dird/conf.d/asset.ldap_service_innactive.yml:/etc/wazo-dird/config.yml"
  slapd:
    image: alpine
    command: "sh -c 'while true; do sleep 10; done'"
