version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - db
    environment:
      TARGETS: "dird:9489 auth:9497 db:5432"
  dird:
    image: wazo-dird-test
    ports:
      - "9489"
    volumes:
      - "./etc/wazo-dird/conf.d/asset.ldap_service_down.yml:/etc/wazo-dird/config.yml"
