version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - america
      - asia
    environment:
      TARGETS: "dird:9489 america:9486 asia:9486 auth:9497"
  dird:
    volumes:
      - "./etc/wazo-dird/conf.d/asset.wazo_users_missing_one_wazo.yml:/etc/wazo-dird/config.yml"
      - "./etc/wazo-dird/sources.d/asset.wazo_users_missing_one_wazo.america.yml:/etc/wazo-dird/sources.d/america.yml"
      - "./etc/wazo-dird/sources.d/asset.wazo_users_missing_one_wazo.asia.yml:/etc/wazo-dird/sources.d/asia.yml"
      - "./etc/wazo-dird/sources.d/asset.wazo_users_missing_one_wazo.europe.yml:/etc/wazo-dird/sources.d/europe.yml"
  america:
    image: python:2.7.13-stretch
    volumes:
      - "./confd_data/asset.wazo_users_missing_one_wazo:/tmp"
    command: "/tmp/run_confd america"
  asia:
    image: python:2.7.13-stretch
    volumes:
      - "./confd_data/asset.wazo_users_missing_one_wazo:/tmp"
    command: "/tmp/run_confd asia"
