version: '3'
services:
  sync:
    depends_on:
      - dird
      - auth
      - db
    environment:
      TARGETS: "dird:9489 auth:9497 db:5432"
  dird:
    volumes:
      - "./etc/wazo-dird/conf.d/asset.sample_backend.yml:/etc/wazo-dird/config.yml"
