version: '3'
services:
  sync:
    depends_on:
      - dird
      - auth
    environment:
      TARGETS: "dird:9489 auth:9497"
  dird:
    image: wazo-dird-test
    ports:
      - "9489"
    volumes:
      - "./etc/wazo-dird/conf.d/asset.broken_display_config.yml:/etc/wazo-dird/config.yml"
      - "./etc/wazo-dird/sources.d/asset.broken_display_config.broken.yml:/etc/wazo-dird/sources.d/broken.yml"
      - "./etc/wazo-dird/sources.d/asset.broken_display_config.my_test_csv.yml:/etc/wazo-dird/sources.d/my_test_csv.yml"
      - "./tmp/data/asset.broken_display_config.test.csv:/tmp/data/test.csv"
