version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
    environment:
      TARGETS: "dird:9489 auth:9497"
  dird:
    volumes:
      - "./etc/wazo-dird/conf.d/asset.xivo_users_no_confd.yml:/etc/wazo-dird/config.yml"
      - "./etc/wazo-dird/sources.d/asset.xivo_users_no_confd.america.yml:/etc/wazo-dird/sources.d/america.yml"
