version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - america
      - europe
      - asia
      - db
    environment:
      TARGETS: "america:9486 asia:9486 europe:9486 dird:9489 auth:9497 db:5432"
  dird:
    volumes:
      - "./etc/wazo-dird/conf.d/asset.wazo_users_multiple_wazo.yml:/etc/wazo-dird/config.yml"
      - "./etc/wazo-dird/sources.d/asset.wazo_users_multiple_wazo.america.yml:/etc/wazo-dird/sources.d/america.yml"
      - "./etc/wazo-dird/sources.d/asset.wazo_users_multiple_wazo.asia.yml:/etc/wazo-dird/sources.d/asia.yml"
      - "./etc/wazo-dird/sources.d/asset.wazo_users_multiple_wazo.europe.yml:/etc/wazo-dird/sources.d/europe.yml"
  america:
    image: python:2.7.13-stretch
    volumes:
      - "./confd_data/asset.wazo_users_multiple_wazo:/tmp"
    command: "/tmp/run_confd america"
  europe:
    image: python:2.7.13-stretch
    volumes:
      - "./confd_data/asset.wazo_users_multiple_wazo:/tmp"
    command: "/tmp/run_confd europe"
  asia:
    image: python:2.7.13-stretch
    volumes:
      - "./confd_data/asset.wazo_users_multiple_wazo:/tmp"
    command: "/tmp/run_confd asia"
