version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - db
    environment:
      TARGETS: "db:5432 dird:9489 auth:9497"
  dird:
    volumes:
      - "./etc/wazo-dird/conf.d/asset.half_broken.yml:/etc/wazo-dird/config.yml"
      - "./tmp/data/asset.half_broken.test.csv:/tmp/data/test.csv"
