version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - db
    environment:
      TARGETS: "db:5432 dird:9489 auth:9497"
  dird:
    volumes:
      - "./etc/wazo-dird/conf.d/asset.config-view.yml:/etc/wazo-dird/config.yml"
      - "./etc/wazo-dird/conf.d/asset.config-view.other.yml:/etc/wazo-dird/conf.d/other.yml"
