version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - db
    environment:
      TARGETS: "dird:9489 auth:9497 db:5432"
  dird:
    volumes:
      - "./etc/wazo-dird/conf.d/asset.phone_view.yml:/etc/wazo-dird/config.yml"
      - "./tmp/data/asset.phone_view.test.csv:/tmp/data/test.csv"
