version: '3'
services:
  sync:
    depends_on:
      - dird
      - auth
    environment:
      TARGETS: "dird:9489 auth:9497"
  dird:
    volumes:
      - "./etc/wazo-dird/conf.d/asset.auth-only.yml:/etc/wazo-dird/config.yml"
