version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      # - confd  # not confd, we WANT it to take time to start
    environment:
      PORTS: "dird:9489 auth:9497"
  dird:
    depends_on:
      - confd
    volumes:
      - "./etc/xivo-dird/conf.d/asset.xivo_users_late_confd.yml:/etc/xivo-dird/config.yml"
      - "./etc/xivo-dird/sources.d/asset.xivo_users_late_confd.america.yml:/etc/xivo-dird/sources.d/america.yml"
  confd:
    image: python:2.7.13-stretch
    volumes:
      - "./confd_data/asset.xivo_users_late_confd:/tmp"
    command: /tmp/run_confd
