version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
    environment:
      TARGETS: "dird:9489 auth:9497"
  dird:
    volumes:
      - "./etc/xivo-dird/conf.d/asset.csv_with_no_unique_column.yml:/etc/xivo-dird/config.yml"
      - "./etc/xivo-dird/sources.d/asset.csv_with_no_unique_column.my_test_csv.yml:/etc/xivo-dird/sources.d/my_test_csv.yml"
      - "./tmp/data/asset.csv_with_no_unique_column.test.csv:/tmp/data/test.csv"
