version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - ws
    environment:
      TARGETS: "ws:9485"
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
  ws:
    image: p0bailey/docker-flask
    ports:
      - "9485"
    volumes:
      - "./scripts/ws.py:/tmp/ws.py"
    command: "python /tmp/ws.py ',' 'iso-8859-1'"
