version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - dird
      - america
      - asia
    environment:
      TARGETS: "dird:9489 america:8000 asia:8000"
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
  dird:
    image: xivo-dird-test
    ports:
      - "9489"
    volumes:
      - "./etc/xivo-dird/config.yml:/etc/xivo-dird/config.yml"
      - "./etc/xivo-dird/sources.d:/etc/xivo-dird/sources.d"
      - "../../..:/usr/src/xivo-dird"
      - "./ssl:/usr/local/share/ssl"
  america:
    image: python:2.7.13-stretch
    volumes:
      - "./confd_data:/tmp"
    command: "/tmp/run_confd america"
  asia:
    image: python:2.7.13-stretch
    volumes:
      - "./confd_data:/tmp"
    command: "/tmp/run_confd asia"
