enabled_plugins:
    backends:
        - csv
    services:
        - lookup
    views:
        - default_json
        - cisco_view

views:
    displays:
        default_display:
            -
                title: Firstname
                field: firstname
            -
                title: Lastname
                field: lastname
            -
                title: Number
                field: number
            -
                title: Favorite
                type: favorite
    displays_phone:
        default:
            name:
                - display_name
            number:
                -
                    field:
                        - phone
    profile_to_display:
        default: default_display

services:
    lookup:
        default:
            sources:
                - test_csv

rest_api:
       listen: 0.0.0.0
       port: 9489
       certificate: /etc/ssl/server.crt
       private_key: /etc/ssl/server.key

auth:
    host: auth
    port: 9497

consul:
    host: consul
    port: 8500
