sync:
  image: n3llyb0y/wait
  links:
    - dird
    - auth
  environment:
    PORTS: "9489 9497"
    TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
dird:
  image: xivo-dird-test
  links:
    - auth
  ports:
    - "9489"
  volumes:
    - "./etc/xivo-dird/config.yml:/etc/xivo-dird/config.yml"
    - "./etc/xivo-dird/sources.d:/etc/xivo-dird/sources.d"
    - "../../..:/usr/src/xivo-dird"
    - "./ssl:/usr/local/share/ssl"
    - "./tmp/data/:/tmp/data"
auth:
  image: p0bailey/docker-flask
  expose:
    - "9497"
  volumes:
    - "./auth_data:/tmp"
    - "./ssl:/usr/local/share/ssl"
  command: "python /tmp/mock-xivo-auth.py 9497"
