enabled_plugins:
  backends:
    csv: true
  services:
    lookup: true
  views:
    default_json: true
    aastra_view: true
    cisco_view: true
    polycom_view: true
    snom_view: true
    thomson_view: true
    yealink_view: true

views:
  displays:
    default_display:
      -
        title: Firstname
        field: firstname
      -
        title: Lastname
        field: lastname
      -
        title: Number
        field: number
      -
        title: Favorite
        type: favorite
  displays_phone:
    default:
      name:
        - display_name
      number:
        -
          field:
            - phone
  profile_to_display:
    default: default_display
  profile_to_display_phone:
    default: default

services:
  lookup:
    default:
      sources:
        - test_csv

rest_api:
  https:
    listen: 0.0.0.0
    port: 9489
    certificate: /usr/local/share/ssl/dird/server.crt
    private_key: /usr/local/share/ssl/dird/server.key

bus:
  enabled: false

service_discovery:
  enabled: false
