sync:
  image: n3llyb0y/wait
  links:
    - auth
    - dird
  environment:
    PORTS: "9489 9497"
    TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
dird:
  image: xivo-dird-test
  ports:
    - "9489:9489"
  volumes:
    - "./etc/xivo-dird/config.yml:/etc/xivo-dird/config.yml"
    - "./etc/xivo-dird/sources.d:/etc/xivo-dird/sources.d"
    - "../../..:/usr/src/xivo-dird"
    - "./ssl:/usr/local/share/ssl"
  links:
    - auth
    - slapd
slapd:
  image: alpine
  command: "sh -c 'while true; do sleep 10; done'"
auth:
  image: p0bailey/docker-flask
  ports:
    - "9497:9497"
  volumes:
    - "./auth_data:/tmp"
    - "./ssl:/usr/local/share/ssl"
  command: "python /tmp/mock-xivo-auth.py 9497"
