sync:
  image: n3llyb0y/wait
  links:
    - dird
  environment:
    PORTS: ""
dird:
  image: xivo-dird-test
  ports:
    - "9489:9489"
  volumes:
    - "./etc/xivo-dird/config.yml:/etc/xivo-dird/config.yml"
    - "./etc/xivo-dird/sources.d:/etc/xivo-dird/sources.d"
    - "../../..:/usr/src/xivo-dird"
    - "./ssl:/usr/local/share/ssl/dird"
